// Fill out your copyright notice in the Description page of Project Settings.


#include "AI/Teacher/TestSoundGenerator.h"
#include "Kismet/GameplayStatics.h"
#include "DrawDebugHelpers.h"
#include "Perception/AISense_Hearing.h" // 헤더 추가

ATestSoundGenerator::ATestSoundGenerator()
{
    PrimaryActorTick.bCanEverTick = true;
}

void ATestSoundGenerator::BeginPlay()
{
    Super::BeginPlay();
}

void ATestSoundGenerator::Tick(float DeltaTime)
{
    Super::Tick(DeltaTime);

    // 에디터 및 게임 실행 중 범위를 시각적으로 표시
    //if (bShowDebugSphere)
    //{
        //DrawDebugSphere(GetWorld(), GetActorLocation(), SoundRange, 32, FColor::Cyan, false, -1.0f, 0, 2.0f);
    //}
}

// TestSoundGenerator.cpp 내 GenerateNoise 함수 수정
void ATestSoundGenerator::GenerateNoise()
{
    // 플레이어 폰을 강제로 주체로 설정
    APawn* NoiseInstigator = GetWorld()->GetFirstPlayerController()->GetPawn();
    if (!NoiseInstigator) return;

    // 확실한 감지를 위해 UAISense_Hearing::ReportNoiseEvent 사용 권장
    MakeNoise(Loudness, NoiseInstigator, GetActorLocation(), SoundRange);
    DrawDebugSphere(GetWorld(), GetActorLocation(), SoundRange, 32, FColor::Red, false, 0.5f, 0, 5.0f);

    UE_LOG(LogTemp, Warning, TEXT("Noise Generated by: %s"), NoiseInstigator ? *NoiseInstigator->GetName() : TEXT("NULL"));
}